# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0856eee8e2835a5b2ea3fe5b4099f37fe8134f326e13bdf9b7d718665aef13bd336995c1817cca20eea164d5b3149273fe765ca1febe29876b481277110238

test:
  secret_key_base: f2609255cf8dd8ba5319b64d487e94d61db83797e0f9e24099c635fc8b855b8666f883a63aa2015c52143562bdbcbca0c3740813a6858998f42a0c7bf0a4c510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
